com.cognizant.framework.FrameworkException: The sub iteration number "2" under iteration number "1" of the test case "TC10" is not found in the test data sheet "General_Data"!
	at com.cognizant.framework.CraftDataTable.getData(CraftDataTable.java:91)
	at businesscomponents.FunctionalComponents.<init>(FunctionalComponents.java:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at supportlibraries.DriverScript.invokeBusinessComponent(DriverScript.java:471)
	at supportlibraries.DriverScript.executeTestcase(DriverScript.java:424)
	at supportlibraries.DriverScript.executeTestIterations(DriverScript.java:378)
	at supportlibraries.DriverScript.driveTestExecution(DriverScript.java:97)
	at allocator.ParallelRunner.invokeTestScript(ParallelRunner.java:59)
	at allocator.ParallelRunner.run(ParallelRunner.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
